# Generated by Django 3.2 on 2021-05-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Contact_no', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Concern', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Contact_no', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Logged_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Contact_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('contact_no', models.CharField(max_length=12, verbose_name='Contact number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name=' Date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
