# Generated by Django 3.2 on 2021-05-23 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Contact_No',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Email',
            new_name='email',
        ),
    ]
