# Generated by Django 3.2 on 2021-05-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20210530_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceList',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.invoice')),
            ],
            bases=('Client.invoice',),
        ),
    ]
