# Generated by Django 3.2 on 2021-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20210523_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_no', models.CharField(max_length=20)),
            ],
        ),
    ]
