# Generated by Django 3.2 on 2021-05-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logged_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Contact_no', models.CharField(max_length=20)),
            ],
        ),
    ]
