# Generated by Django 3.2 on 2021-05-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_auto_20210530_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Amount_Due',
            field=models.CharField(default='0.0', max_length=20),
        ),
    ]
