# Generated by Django 3.2 on 2021-05-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_invoice_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Concern',
            field=models.CharField(choices=[('Concerns', 'Concerns'), ('General Check-Up', 'General Check-Up'), ('Oral Prophylaxis', 'Oral Prophylaxis'), ('Tooth Restoration', 'Tooth Restoration'), ('Tooth Extraction', 'Tooth Extraction'), ('Odontectomy', 'Odontectomy'), ('Root Canal Treatment', 'Root Canal Treatment'), ('Full and Partial Dentures', 'Full and Partial Dentures'), ('Fixed Bridge', 'Fixed Bridge'), ('Veneers', 'Veneers'), ('Jacket Crowns', 'Jacket Crowns')], default='Concerns', max_length=60),
        ),
    ]
