# Generated by Django 3.2 on 2021-05-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_alter_invoice_concern'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceRecords',
        ),
    ]
