# Generated by Django 3.2 on 2021-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=30),
        ),
    ]
