# Generated by Django 3.2 on 2021-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dentist_Acct', '0002_auto_20210419_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist_acct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
