# Generated by Django 3.2 on 2021-05-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dentist_Acct', '0004_auto_20210503_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist_acct',
            name='Clients',
        ),
        migrations.AlterField(
            model_name='dentist_acct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
