# Generated by Django 3.2 on 2021-05-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dentist_Acct', '0005_alter_dentist_acct_id'),
        ('Dentist_Acct', '0005_auto_20210524_2206'),
    ]

    operations = [
    ]
